# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      #- image: circleci/python:3.6.1
      - image: circleci/ubuntu-server
      
    #working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "requirements.txt" }}
      #    # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      #- run:
<<<<<<< HEAD
      #    name: build and push docker images 
=======
      #    name: install dependencies
>>>>>>> e4bb7e59ac514f36cf29280013cbd5bf7caed1e3
      #    command: |
      #      python3 -m venv venv
      #k      . venv/bin/activate
      #      pip install -r requirements.txt

      #- save_cache:
      #    paths:
      #      - ./venv
      #    key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - type: setup-docker-engine
      - type: shell

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t firefoxtesteng/shavar-loadtests:latest .
              docker push firefoxtesteng/shavar-loadtests:latest
            else
              docker build -t firefoxtesteng/shavar-loadtests:$CIRCLE_BRANCH .
              docker push firefoxtesteng/shavar-loadtests:$CIRCLE_BRANCH
            fi

